# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/moto8937_n/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/motorola/moto8937_n

PRODUCT_COPY_FILES += \
    vendor/motorola/moto8937_n/proprietary/vendor/firmware/libpn548ad_fw.so:$(TARGET_COPY_OUT_VENDOR)/firmware/libpn548ad_fw.so \
    vendor/motorola/moto8937_n/proprietary/vendor/firmware/synaptics-inx-s3603r-17042001-27111d-montana.tdat:$(TARGET_COPY_OUT_VENDOR)/firmware/synaptics-inx-s3603r-17042001-27111d-montana.tdat \
    vendor/motorola/moto8937_n/proprietary/vendor/firmware/synaptics-tianma-s3603r-17041102-27111d-montana.tdat:$(TARGET_COPY_OUT_VENDOR)/firmware/synaptics-tianma-s3603r-17041102-27111d-montana.tdat \
    vendor/motorola/moto8937_n/proprietary/vendor/lib64/hw/gatekeeper.msm8937.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/gatekeeper.msm8937.so \
    vendor/motorola/moto8937_n/proprietary/vendor/lib64/hw/keystore.msm8937.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/keystore.msm8937.so
